//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUS_Cadastral_Tools.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AUS_Cadastral_Tools.Strings.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Position or:.
        /// </summary>
        internal static string AcceptPositionOr {
            get {
                return ResourceManager.GetString("AcceptPositionOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing.
        /// </summary>
        internal static string Bearing {
            get {
                return ResourceManager.GetString("Bearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance between points: .
        /// </summary>
        internal static string DistanceBetweenPoints {
            get {
                return ResourceManager.GetString("DistanceBetweenPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load CUI file.
        /// </summary>
        internal static string ErrorCUIFile {
            get {
                return ResourceManager.GetString("ErrorCUIFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip bearing?.
        /// </summary>
        internal static string FlipBearing {
            get {
                return ResourceManager.GetString("FlipBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First intersection found at X:{0} Y:{1}.
        /// </summary>
        internal static string FoundFirstIntersection {
            get {
                return ResourceManager.GetString("FoundFirstIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second intersection found at X:{0} Y:{1}.
        /// </summary>
        internal static string FoundSecondIntersection {
            get {
                return ResourceManager.GetString("FoundSecondIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersection found at X:{0} Y:{1}.
        /// </summary>
        internal static string IntersectionAtXY {
            get {
                return ResourceManager.GetString("IntersectionAtXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity type.
        /// </summary>
        internal static string InvalidEntity {
            get {
                return ResourceManager.GetString("InvalidEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metres.
        /// </summary>
        internal static string Metres {
            get {
                return ResourceManager.GetString("Metres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No intersection point found!.
        /// </summary>
        internal static string NoIntersection {
            get {
                return ResourceManager.GetString("NoIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick near desired intersection point:.
        /// </summary>
        internal static string PickIntersection {
            get {
                return ResourceManager.GetString("PickIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select first line to offset:.
        /// </summary>
        internal static string SelectFirstOffsetLine {
            get {
                return ResourceManager.GetString("SelectFirstOffsetLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select second line to offset:.
        /// </summary>
        internal static string SelectSecondOffsetLine {
            get {
                return ResourceManager.GetString("SelectSecondOffsetLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope.
        /// </summary>
        internal static string Slope {
            get {
                return ResourceManager.GetString("Slope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify base point: .
        /// </summary>
        internal static string SpecifyBasePoint {
            get {
                return ResourceManager.GetString("SpecifyBasePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify bearing:.
        /// </summary>
        internal static string SpecifyBearing {
            get {
                return ResourceManager.GetString("SpecifyBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify bearing on screen:.
        /// </summary>
        internal static string SpecifyBearingOnScreen {
            get {
                return ResourceManager.GetString("SpecifyBearingOnScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify bearing or:.
        /// </summary>
        internal static string SpecifyBearingOr {
            get {
                return ResourceManager.GetString("SpecifyBearingOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify distance:.
        /// </summary>
        internal static string SpecifyDistance {
            get {
                return ResourceManager.GetString("SpecifyDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify distance along line:.
        /// </summary>
        internal static string SpecifyDistanceAlongLine {
            get {
                return ResourceManager.GetString("SpecifyDistanceAlongLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify distance in {0} or:.
        /// </summary>
        internal static string SpecifyDistanceInOr {
            get {
                return ResourceManager.GetString("SpecifyDistanceInOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify first bearing:.
        /// </summary>
        internal static string SpecifyFirstBearing {
            get {
                return ResourceManager.GetString("SpecifyFirstBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify first distance:.
        /// </summary>
        internal static string SpecifyFirstDistance {
            get {
                return ResourceManager.GetString("SpecifyFirstDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify first point:.
        /// </summary>
        internal static string SpecifyFirstPoint {
            get {
                return ResourceManager.GetString("SpecifyFirstPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify fourth point:.
        /// </summary>
        internal static string SpecifyFourthPoint {
            get {
                return ResourceManager.GetString("SpecifyFourthPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify inches:.
        /// </summary>
        internal static string SpecifyInches {
            get {
                return ResourceManager.GetString("SpecifyInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify left offset distance:.
        /// </summary>
        internal static string SpecifyLeftOffsetDistance {
            get {
                return ResourceManager.GetString("SpecifyLeftOffsetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify line or polyline segment:.
        /// </summary>
        internal static string SpecifyLineOrPolylineSegment {
            get {
                return ResourceManager.GetString("SpecifyLineOrPolylineSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify offset distance:.
        /// </summary>
        internal static string SpecifyOffsetDistance {
            get {
                return ResourceManager.GetString("SpecifyOffsetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify point on side to offset:.
        /// </summary>
        internal static string SpecifyOffsetSide {
            get {
                return ResourceManager.GetString("SpecifyOffsetSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify right offset distance:.
        /// </summary>
        internal static string SpecifyRightOffsetDistance {
            get {
                return ResourceManager.GetString("SpecifyRightOffsetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify second bearing:.
        /// </summary>
        internal static string SpecifySecondBearing {
            get {
                return ResourceManager.GetString("SpecifySecondBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify second distance:.
        /// </summary>
        internal static string SpecifySecondDistance {
            get {
                return ResourceManager.GetString("SpecifySecondDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify second point:.
        /// </summary>
        internal static string SpecifySecondPoint {
            get {
                return ResourceManager.GetString("SpecifySecondPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify third point:.
        /// </summary>
        internal static string SpecifyThirdPoint {
            get {
                return ResourceManager.GetString("SpecifyThirdPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify units:.
        /// </summary>
        internal static string SpecifyUnits {
            get {
                return ResourceManager.GetString("SpecifyUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
    }
}
